library(tm)  
library(RTextTools)
library(SnowballC)
library(wordcloud)
#change parameters to your needs
dataDirectory <- "/home/radiohead/Documents/"
data <- read.csv(paste(dataDirectory, 'data_R_training.csv', sep=""), header = TRUE)
docs_training <- Corpus(DataframeSource(data["description"]))
docs_training <- tm_map(docs_training, removePunctuation)
docs_training <- tm_map(docs_training, removeNumbers)
docs_training <- tm_map(docs_training, tolower)
docs_training <- tm_map(docs_training, removeWords, c(stopwords("english"), "huf", "also", "info", "event", "day", "budapest", "hungary", "hungarian", "xexx", "txcxar"))
docs_training <- tm_map(docs_training, stemDocument)
docs_training <- tm_map(docs_training, stripWhitespace)
docs_training <- tm_map(docs_training, PlainTextDocument)
data_frame <- data.frame(text = sapply(docs_training, paste, collapse = " "), stringsAsFactors = FALSE)
#trace("create_matrix", edit=T)
dt_matrix <- create_matrix(data_frame)
container <- create_container(dt_matrix, data$category, trainSize=1:length(docs_training), virgin=FALSE)
model <- train_model(container, "SVM")

#testing
data_test <- read.csv(paste(dataDirectory, 'data_R_test.csv', sep=""), header = TRUE)
docs_test <- Corpus(DataframeSource(data_test))
docs_test <- tm_map(docs_test, removePunctuation)
docs_test <- tm_map(docs_test, removeNumbers)
docs_test <- tm_map(docs_test, tolower)
docs_test <- tm_map(docs_test, removeWords, c(stopwords("english"), "huf", "also", "info", "event", "day", "budapest", "hungary", "hungarian", "xexx", "txcxar"))
docs_test <- tm_map(docs_test, stemDocument)
docs_test <- tm_map(docs_test, stripWhitespace)
docs_test <- tm_map(docs_test, PlainTextDocument)
data_frame_test <- data.frame(text = sapply(docs_test, paste, collapse = " "), stringsAsFactors = FALSE)
prediction_data <- split(data_frame_test, seq(nrow(data_frame_test)))
#prediction_data <- list("music", "sport football", "food")
prediction_matrix <- create_matrix(prediction_data, originalMatrix=dt_matrix)
prediction_size = length(prediction_data);
prediction_container <- create_container(prediction_matrix, labels=rep(0,prediction_size), testSize=1:prediction_size, virgin=FALSE)
results <- classify_model(prediction_container, model)

#fancy stuff
dataDirectory <- "/home/radiohead/Documents/"
data_raw <- read.csv(paste(dataDirectory, 'data_R.csv', sep=""), header = TRUE)
docs_raw <- Corpus(DataframeSource(data_raw["description"]))
docs_raw <- tm_map(docs_raw, removePunctuation)
docs_raw <- tm_map(docs_raw, removeNumbers)
docs_raw <- tm_map(docs_raw, tolower)
docs_raw <- tm_map(docs_raw, removeWords, c(stopwords("english"), "huf", "also", "info", "event", "day", "budapest", "hungary", "hungarian", "xexx", "txcxar"))
docs_raw <- tm_map(docs_raw, stemDocument)
docs_raw <- tm_map(docs_raw, stripWhitespace)
docs_raw <- tm_map(docs_raw, PlainTextDocument)
dtm <- DocumentTermMatrix(docs_raw)
freq <- colSums(as.matrix(dtm))   
dark2 <- brewer.pal(6, "Paired")   
wordcloud(names(freq), freq, max.words=50, rot.per=0.3, colors=dark2)   
